### PR TITLE
project CI refresh

### PR DESCRIPTION
**Pull request by cpu**
Continuing the CI standardization and refresh started in https://github.com/rusticata/rusticata-macros/pull/8

### CODE REVIEW

**Comment by cpu** [comment]
@chifflier I think this one is ready for review now. Adding CI coverage for the MSRV of 1.63 required some care. This crate has two transitive dependencies that have bumped their MSRV within otherwise semver compatible versions:

* `winnow` [0.4.2+](https://github.com/winnow-rs/winnow/blob/v0.6.6/CHANGELOG.md#042---2023-04-28) requires an MSRV of 1.64.0
* `toml_edit` [0.19.9+](https://github.com/toml-rs/toml/blob/main/crates/toml_edit/CHANGELOG.md#0199---2023-05-18) requires an MSRV of 1.64.0

Recently the Rust project [guidance on commiting lockfiles](https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html) for library projects was changed and they now leave it up to individual projects, saying: "A lockfile is an appropriate way to pin versions for your project so you can validate your MSRV"

I generally like that approach and it works well in some other repos I contribute to. As a result I've opted to commit a lockfile and use `--locked` in CI to maintain MSRV here. I think this is a better approach than manually working around the issue with `cargo update --precise` and is in-line with current best practices, but I also know it's a deviation from how you've otherwise done things. What do you think? Should I drop the lockfile and fix this another way?

**Comment by chifflier** [comment]
Hi,
Thank you for the PR and the information. I am still wondering what is best, given that previously, the rust documentation stated that `Cargo.lock` should not be committed for libraries.

If I understand correctly, this changed last year, mostly for reasons similar to the problems we are encountering.
I think it's interesting to build with locked dependencies, but it is also interesting to build without `--locked`, to detect when an dependencies breaks build (like in https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-latest-dependencies).

Maybe the best solution would be add yet another test in CI (something like weekly or daily?) to test build with latest dependencies, in addition to the `--locked` builds.

**Comment by cpu** [comment]
> Maybe the best solution would be add yet another test in CI (something like weekly or daily?) to test build with latest dependencies, in addition to the --locked builds.

I'm open to that, but I think it will immediately error for this crate based on the situation being avoided with the lockfile. Should I go ahead and add that task?

**Comment by cpu** [comment]
>> Maybe the best solution would be add yet another test in CI (something like weekly or daily?) to test build with latest dependencies, in addition to the --locked builds.
> 
> I'm open to that, but I think it will immediately error for this crate based on the situation being avoided with the lockfile.

I think I confused myself here and it would be fine. We just wouldn't use the MSRV rust version for this test, using stable instead (?)

**Comment by chifflier** [comment]
> > > Maybe the best solution would be add yet another test in CI (something like weekly or daily?) to test build with latest dependencies, in addition to the --locked builds.
> > 
> > 
> > I'm open to that, but I think it will immediately error for this crate based on the situation being avoided with the lockfile.
> 
> I think I confused myself here and it would be fine. We just wouldn't use the MSRV rust version for this test, using stable instead (?)

The non-locked version should probably be on stable.
That said, I'm also confused for `Cargo.lock`: which version should we commit? The one that can build MSRV (but will be old), or the one for stable? or both?

**Comment by cpu** [comment]
>  The one that can build MSRV (but will be old)

Correct, it would be this one, but not all the deps will be pinned to old versions. Just the deps that can't be updated past a specific version without changing the MSRV. In this case, just `winnow` and `toml_edit`

**Comment by chifflier** [comment]
> > The one that can build MSRV (but will be old)
> 
> Correct, it would be this one, but not all the deps will be pinned to old versions. Just the deps that can't be updated past a specific version without changing the MSRV. In this case, just `winnow` and `toml_edit`

Ok, fair enough, thank you for the explanation. 
Let's merge this!

**Pull request merged**
